set(CMAKE_C_COMPILER "gcc-11" CACHE STRING "")
set(CMAKE_CXX_COMPILER "g++-11" CACHE STRING "")

set(CMAKE_BUILD_TYPE "Release" CACHE STRING "")
set(BUILD_SHARED_LIBS ON CACHE BOOL "")

set(LLVM_CCACHE_BUILD ON CACHE BOOL "")
set(LLVM_CCACHE_DIR "/cache/ccache" CACHE STRING "")

set(LLVM_TARGETS_TO_BUILD "Native" CACHE STRING "")
set(LLVM_ENABLE_PROJECTS "clang;clang-tools-extra" CACHE STRING "")
set(LLVM_ENABLE_RUNTIMES "openmp" CACHE STRING "")

set(LLVM_INCLUDE_TESTS OFF CACHE BOOL "")
set(LLVM_INCLUDE_BENCHMARKS OFF CACHE BOOL "")
set(LLVM_INCLUDE_EXAMPLES OFF CACHE BOOL "")
